### ISSUE TITLE
Activate and test new theme

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/clarity-theme#1]
The new theme has been installed in CSIS Container at /app/web/themes/custom/clarity and can be updated by user docker via git pull. It still has to be activated in the Drupal admin UI.

This issue is currently on-hold till after the next plenary meeting (2019-07-03-05).

@bullz @DanielRodera 
Is there a possibility to test the new theme it in a local CSIS instance and additional make some screenshots that we can present to users during the meeting?

**Comment by bullz** [comment]
@p-a-s-c-a-l 
About the activation of the new theme there are some steps needed:

1.	Activate the theme
2.	Set the blocks as the image “blocks.png”
3.	Create new instance page of the view: **adaptation_options_overview** with the global:custom text code:
![Screenshot from 2019-07-02 11-25-04](https://user-images.githubusercontent.com/160349/60501411-4b24d300-9cbc-11e9-90e3-6dba96d784b4.png)

**Block settings** :
![blocks](https://user-images.githubusercontent.com/160349/60501459-6263c080-9cbc-11e9-83be-e681a3262920.png)

**Screenshots:**
![front_1](https://user-images.githubusercontent.com/160349/60501534-78718100-9cbc-11e9-9890-b078a353bc12.jpg)
![front_2](https://user-images.githubusercontent.com/160349/60501544-7dcecb80-9cbc-11e9-8dc0-9882b5aac4fe.jpg)
![introduction](https://user-images.githubusercontent.com/160349/60501545-80312580-9cbc-11e9-8d5e-4feafe5a6092.jpg)
![maps](https://user-images.githubusercontent.com/160349/60501550-81fae900-9cbc-11e9-9027-3d97c83afd73.jpg)
![adaptation](https://user-images.githubusercontent.com/160349/60501558-845d4300-9cbc-11e9-8f9f-383ec7936f2c.jpg)

![view](https://user-images.githubusercontent.com/160349/60501641-a2c33e80-9cbc-11e9-8e25-53f66047e845.png)

**Comment by patrickkaleta** [comment]
I installed the new clarity theme, configured the block layout and created the [new View display](https://csis.myclimateservice.eu/admin/structure/views/view/adaptation_options_overview/edit/page_2) for Adaptation options overview (but left disabled for now) as explained by @bullz.

### Activating new theme
Setting the new theme as default [here](https://csis.myclimateservice.eu/admin/appearance) actually enables it on the website for the end-users.
![set-default-theme](https://user-images.githubusercontent.com/42167036/63022858-16ec2700-bea4-11e9-9403-e8eb96302fd5.png)

### Important
Changing back and forth between the new clarity theme and the old csis theme should not cause any problems (just use the link above and set the respective theme "as default". I already did that a couple of times on the CSIS server). **Just don't use the "Uninstall" button**, since that would remove all configuration (like the block layout etc) of that theme.

### Next
During testing I already noticed some smaller issues (although in general it all seems to be working just fine). I will subsequently create issues for those problems and mainly assign them to @bullz, @DanielRodera and probably myself.

@DanielRodera, @bullz: the inial commit in this repository is already two months old. Have there been any changes in the code during that time or is this now the current and up-to-date version of the theme?

**Comment by patrickkaleta** [comment]
Just switched to the new theme permanently now. Switching back to the old csis theme always possible by setting it as the default theme (explained [above](https://github.com/clarity-h2020/clarity-theme/issues/1#issuecomment-521239300)).

Closing this issue now. Any bugs/problems with the new theme will be addressed in separate issues.
