### ISSUE TITLE
New style for CSIS CLARITY theme

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/clarity-theme#17]
@bullz made a few changes in clarity theme already uploaded to [GitHub](https://github.com/clarity-h2020/clarity-theme/commit/bb3d188c7766bd5389c27726568290ffd813aa8f)
For correct display there should be some changes in administration:

### Create custom block Welcome to CLARITY CSIS - Climate Services Information System with this content:

- Title: `Welcome to CLARITY CSIS - Climate Services Information System`
- Content:
``` html
<h2>Plan by stages</h2>

<p>We create awareness of the CLARITY climate service, case studies, demonstrators and tools among relevant stakeholders in the climate and urban infrastructure planning and management sector, industries and civil society. We build up and foster the CLARITY Community with regional experts and contact points. We analyse and provide data relevant to stakeholders, share knowledge and connect the CLARITY Community.</p>

<ol>

    <li><strong>Development of the eu-project Clarity</strong> CLARITY is the first point of reference and the most important information, service and collaboration hub for everybody being concerned with climate change impact assessment in Europe.</li>

    <li><strong>Onboarding of further partners</strong> We foster a CLARITY Community involving local target sectors and stakeholders that are interested in CLARITY scenarios. Either as host of events, regional experts or contact point for tools and services.</li>

    <li><strong>Roll-out of the fullversion of the marketplace</strong> CLARITY's value proposition is to make climate-proofing of infrastructure easier and faster at a fraction of the cost of individual climate sensitivity, vulnerability impact and adaption startegy studies.</li>

</ol>
```

### Create Our goal custom block:

- Title: `Our goal`
- Content:
```html
<p>Development, operation and dissemination of a digital marketplace providing services, contents, features and tools for the climate change impact assessment, which have been developed on the base of scientific data and meet the new European standards and regulations.</p>
```
- In the slideshow view modify: FORMAT > SHOW: FIELDS SETTINGS: uncheck Provide default field wrapper elements
- Place the blocks into the Front Content region:
  - Slideshow: Frontpage (moved from content region)
  - Our goal
  - Welcome to CLARITY CSIS - Climate Services Information System
  - Study Group Overview: All studies Table Block    (moved from content region)

**Comment by bullz** [comment]
Another thing:
Remove the slideshow view BOOTSTRAP classes "col-sm-12" from the <strong>other > CSS class</strong> option

**Comment by patrickkaleta** [comment]
@bullz 
Thank you for the detailed description. Just for the sake of documentation, I'd like to add that the body field of the [welcome page](http://csis.myclimateservice.eu/node/102/edit) needs to be removed, otherwise the texts are shown twice on the front page.

However, it seems that for the slideshow some of the styling is now missing - titles and control buttons don't have any styling applied anymore. Original styling was removed in latest theme update (row [ 3701](https://github.com/clarity-h2020/clarity-theme/commit/bb3d188c7766bd5389c27726568290ffd813aa8f#diff-6a6a912d0c7b55b537768da778032849L3701) onwards).

Therefore, I haven't activated the new theme updates on https://csis.myclimateservice.eu. But you can see it on our new [Dev server](https://csis-dev.ait.ac.at/). Please check what's going wrong/ is missing in the newest theme update.

**Comment by patrickkaleta** [comment]
@bullz 
also could you please post some screenshots of different pages with the new theme updates on your local machine? That will make it easier to check if everything is applied properly on the live website.

**Comment by patrickkaleta** [comment]
@bullz I made a couple of small adjustments in the new theme update, so please make sure to pull these changes first before you continue working on the theme.

**Comment by bullz** [comment]
<p>The slideshow block was different from my working version.</p>

<p>I've made some changes and also there are some things to add from administration:</p>

<ul>
	<li>In the slideshow view modify:
	<ul>
		<li>Remove Css class: from “other” col-sm-12</li>
		<li>In FIELDS &gt; CONTENT: TITLE field add STYLE SETTINGS &gt; CUSTOMIZE FIELD HTML &gt; H3</li>
	</ul>
	</li>
	<li>Remove the content from node/102</li>
	<li>Configure PAGE TITLE block for hide the &lt;front&gt; content</li>
</ul>

<p>Please check my last COMMIT to DEV</p>

**Comment by patrickkaleta** [comment]
thanks @bullz! I deployed your latest commit. It looks better now, but I'm still not sure if it everything is now configured properly. Please check the website and compare it with your local instance and let me know what else needs to be changed in the configuration of the website.  

One of the more urgent things that still need to be fixed in the theme is the missing cancel button in our forms ([more info](https://github.com/clarity-h2020/clarity-theme/issues/11#issuecomment-589651452)). @bullz please also have a look at that.

**Comment by bullz** [comment]
I think everything was configured ok, for some reason the Slideshow id block name is different, I just added the Id from the server, it should work now with the [last commit](https://github.com/clarity-h2020/clarity-theme/commit/5eae11a7450d6f5f56f6293a03921b641f4a5f14).

About the button I added the bootstrap ui classes (except _tabs_ and _accordion_ which are being stylize elsewhere), It should also work now.

**Comment by patrickkaleta** [comment]
> I think everything was configured ok, for some reason the Slideshow id block name is different, I just added the Id from the server, it should work now with the [last commit](https://github.com/clarity-h2020/clarity-theme/commit/5eae11a7450d6f5f56f6293a03921b641f4a5f14).

Yes, now it looks even better. Only thing remaining is a missing "Pause" text in the slideshow navigation. Maybe another problem with a differently named block ID?

> 
> About the button I added the bootstrap ui classes (except _tabs_ and _accordion_ which are being stylize elsewhere), It should also work now.

Perfect! The cancel button is back :)

**Comment by bullz** [comment]
The pause button needs to load new font so refreshing the browser with **ctrl+F5** should work

**Comment by patrickkaleta** [comment]
You're right. The pause button is now visible. So the new theme update is now active on the CSIS website. We can close this issue now
