### ISSUE TITLE
HTML List elements break layout

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#6]
When viewing the details of an included Twin in the [summary](https://csis.myclimateservice.eu/study/1/step/2/view/summary) tab, the layout breaks for certain Twins:
![ol-breaks-layout](https://user-images.githubusercontent.com/42167036/63431932-54126500-c420-11e9-9324-ea53e4e76271.png)
The shown Twin in this case contains an ordered list `<ol>`, which seems to be responsible for this bug. Removing the `<ol>` element lets the Twin shrink back to a fitting width.

**Comment by patrickkaleta** [comment]
In addition I noticed that list elements (at  least for unordered lists) are not properly displayed (for example [here](https://csis.myclimateservice.eu/solution-offers)):
![missing-ol-styling](https://user-images.githubusercontent.com/42167036/67378013-d9cca100-f586-11e9-8407-80603e4865cc.png)

Elements are just listed one below the other without any visual hint (a dot or a hyphen) which would make it clear that those are all individual elements and not one text paragraph.

@bullz please fix this and add some styling to list elements.

**Comment by bullz** [comment]
unordered lists in views back to normal display, also some changes in table display (smaller font, zebra stripes) on this [commit](https://github.com/clarity-h2020/clarity-theme/commit/85cf8743fdf7e6b28575ce34fdfc3313ee590747)

**Comment by bullz** [comment]
The layout breaks on some content because of long links, instead of put the full link into the link text such as:

- <a href="http://archiviostorico.corriere.it/2013/novembre/26/Sardegna_stimati_danni_per_oltre_co_0_20131126_384f4fb4-5666-11e3-8656-1d64ae9d6504.shtml">http://archiviostorico.corriere.it/2013/novembre/26/Sardegna_stimati_danni_per_oltre_co_0_20131126_384f4fb4-5666-11e3-8656-1d64ae9d6504.shtml</a>
the correct way would be something like this:

- <a href="http://archiviostorico.corriere.it/2013/novembre/26/Sardegna_stimati_danni_per_oltre_co_0_20131126_384f4fb4-5666-11e3-8656-1d64ae9d6504.shtml">article at archiviostorico.corriere.it</a>

But I uploaded some CSS to prevent long links to break content on this [commit](https://github.com/clarity-h2020/clarity-theme/commit/233b5295941c42885a6340e7bb5b0ec634c5756f)

**Comment by patrickkaleta** [comment]
These issues have been solved in @bullz latest theme update.
