### ISSUE TITLE
Improve Data package views

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#7]
As explained [here](https://github.com/clarity-h2020/docker-drupal/issues/47#issuecomment-522973855) the appearance of this tab needs to be improved.
Example link, where this tab is used: https://csis.myclimateservice.eu/study/1/step/2/view/data

**Some thoughts:**
- the elements ("temperature", "heat-wave", "HI_Tx75p-consecutive-max...", etc) are actually clickable, but the user has no idea about that since they appear as ordinary text to him
- those elements have a hierarchy (Level 0 - "temperature", level 1 - "heat",....), so some sort of indentation could be useful

**Jump to https://github.com/clarity-h2020/clarity-theme/issues/7#issuecomment-537516564 for idea how to handle this.**

**Comment by patrickkaleta** [comment]
Latest [changes](https://github.com/clarity-h2020/clarity-theme/commit/e9bde83dce54a2a2c82eacf7da7c240e90835157) by @bullz meant some improvements, but I think we are still not quite done here.

The styling for the `.item-preview` doesn't seem to be correct compared to the provided [screenshot](https://github.com/clarity-h2020/docker-drupal/issues/47#issuecomment-530254719).

In addition, this view shows not only resources (content entities), but also hazards (taxonomy terms), which have a hierarchy. I think it would be good to show this hierarchy on that page as well. Also the taxonomy terms themselves can also be clicked on and they provide an item-preview as well.
![improve-datapackage-view](https://user-images.githubusercontent.com/42167036/65314226-327ad980-db96-11e9-9638-1417fa470502.png)

**Comment by bullz** [comment]
I think I need some help on where this code is generated, I can't find it. this HTML needs to change to proper styling without too much CSS hacking

**Comment by patrickkaleta** [comment]
> I think I need some help on where this code is generated, I can't find it. this HTML needs to change to proper styling without too much CSS hacking

This is all created in some nested View calls. @fgeyer16 took care of implementing this, he can list you the involved views and the order in which they are called.

**Comment by DenoBeno** [comment]
It's generated in https://csis.myclimateservice.eu/admin/structure/views/view/step_data_collection_2/edit/entity_view_1

Which is probably something we should "kill" in order to get more flexibility. 
https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display/data?destination=/contextual/render&destination=/study/35/step/1530/view/data

![image](https://user-images.githubusercontent.com/2961790/66039679-cf822e80-e515-11e9-8f3c-63d823a37e4c.png)

Instead of this, we should do the same as in other steps - ideally in the same way as we did for the tables in the identify adaptation options step (e.g. https://csis.myclimateservice.eu/study/35/step/1526/view/table)

![image](https://user-images.githubusercontent.com/2961790/66039934-7ebf0580-e516-11e9-9be8-f7ae541ddced.png)

https://csis.myclimateservice.eu/admin/content?title=&type=view_as_application&status=All&langcode=All

![image](https://user-images.githubusercontent.com/2961790/66039992-9f875b00-e516-11e9-93c7-07e008dcbc94.png)

https://csis.myclimateservice.eu/node/1286/edit

![image](https://user-images.githubusercontent.com/2961790/66040028-bb8afc80-e516-11e9-926c-1b9f675013d9.png)

Alternatively, we could do it as twins are implemented - use view field directly in GL-step. Saves us one level of redirection but makes it more difficult to configure templates and doesn't allow to use external applications.

**Comment by fgeyer16** [comment]
This is related to [this issue](https://github.com/clarity-h2020/csis/issues/106) (can we merge them somehow?)
As @DenoBeno already said there we have also a multiplication issue due to multiple Terms for a single resource. I do not think that restricting to one term would be a good idea so I propose a solution, which does not show all matches or how ever you want to name it initially. What I have in mind is something accordion like which it is used here: http://cfe-zertifizierung.at/measures.
Since only one Term is open at one moment nobody will be confused on the dupicates. 
And the view we need is much better to understand since it is a simple view with only set grouping to the categorisation field (https://csis.myclimateservice.eu/admin/structure/views/view/step_data_collection_2/edit/entity_view_2) and not such a monster as it is the current used view.
If wanded I can provide the twig file and maybe the js (there is used jquery or bootstrap.js )

**Comment by DenoBeno** [comment]
I have closed https://github.com/clarity-h2020/csis/issues/106, so consider them merged now.

**Comment by DenoBeno** [comment]
What I'm wondering is if we should allow people to choose some of the resources and include them to the report, like we do for the adaptation options now.

see e.g. https://csis.myclimateservice.eu/study/33/step/1515/view/table

This is my proposal on how the new "data" tab could look like. Just like for the twins, we will probably  end up using different views for different steps, so I recommend to resolve what is shown where in the same way as it's done for the tables now.

![image](https://user-images.githubusercontent.com/2961790/66108249-77553600-e5c2-11e9-99c3-3b078747552e.png)

The report should IMO contain details only for the chosen resources (in the section where they were chosen) and just a basic information for the all resources in the data package in a separate section (annex).

**Reminder:** we also need to include the "pseudo resources" in the data tabs and in the annex listing all resources. That's the adaptation options and the vulnerability functions. I believe that we can use the already existing views that are currently under "table" for this purpose (with minimal changes).

**Comment by bullz** [comment]
The style has been lost, I think the view has changed. Should I look into it and try to fix it?

**How it looks in local**:
![data](https://user-images.githubusercontent.com/160349/66299133-39724d80-e8f3-11e9-93f3-a7a12ede6973.png)

**How it looks in server now**:
![data_online](https://user-images.githubusercontent.com/160349/66299190-5575ef00-e8f3-11e9-8ec2-5b41ae1ec095.png)

**Comment by patrickkaleta** [comment]
> The style has been lost, I think the view has changed. Should I look into it and try to fix it?

Just take a quick look and see if you can spot the change (I'm assuming probably a CSS class has been renamed or removed). It would be nice to get at least the "button-like" background for each term back, but don't invest too much of your time into that. 

Reading through this thread it looks like the whole data package view will be undergoing some major changes in the near future, so trying to **completely** fix this now would be a waste of time IMO.

**Comment by bullz** [comment]
The view changed, so I added styles for the new classes in a [new commit](https://github.com/clarity-h2020/clarity-theme/commit/ac6edbcce82eca0c08b512a78e2a855bc64c0486)

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
Closing this (styling is IMO ok, so nothing else to do here regarding the theme) and starting a [separate issue](https://github.com/clarity-h2020/csis/issues/146) about what the Data tab should look/behave like.
